### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by quaff** [webauthn4j/webauthn4j-spring-security#101]
I'm using macOS Catalina and https://github.com/github/SoftU2F as soft authenticator, [yubico WebAuthn](https://demo.yubico.com/webauthn-technical/registration)  demo passed, both with latest stable chrome 78.0.3904.87 and firefox 70.0.1.
With `spring-security-webauthn`, both chrome and firefox works fine for registeration, but not working for login, chrome failed wake up `SoftU2F`, and firefox can wake up `SoftU2F` but failed with `Authentication failed with InvalidStateError`

**Comment by M3lkior** [comment]
Same issue here

**Comment by ynojima** [comment]
Sorry for belated reply.
I haven't tested with `SoftU2F`. I'll check, but I'm out for business trip for 2weeks.

**Comment by ynojima** [comment]
It sounds like a issue about `SoftU2f` not about `Mac OS`. Have you confirmed `SoftU2F` work with `windows` or other platform?

**Comment by quaff** [comment]
`SoftU2F` works fine with [Yubico demo](https://github.com/Yubico/java-webauthn-server/tree/master/webauthn-server-demo) on macOS.
