### ISSUE TITLE
Should AttestationOptionsEndpointFilter be provided as a Controller?

### ISSUE THREAD

**Issue by blacelle** [webauthn4j/webauthn4j-spring-security#1011]
_based on https://github.com/webauthn4j/webauthn4j/issues/700_

**Is your feature request related to a problem? Please describe.**
I'm considering relying on this library to implement WebAuthn in our project. However, we encounter some difficulties in its integration. One of them is wiring WebAuthn4J inside an existing application with a complex security layer (e.g. multiple existing WebSecurityConfigurerAdapter).

While we initially added an additional WebSecurityConfigurerAdapter dedicated to WebAuthn4J purposes, it does not work as simply as that as AttestationOptionsEndpointFilter has to receive a proper Authentication (from a not-WebAuthn4J filter) to return a proper userId.

com.webauthn4j.springframework.security.options.AttestationOptionsProviderImpl.DefaultPublicKeyCredentialUserEntityProvider.provide(Authentication)

    static class DefaultPublicKeyCredentialUserEntityProvider implements PublicKeyCredentialUserEntityProvider {

        @Override
        public PublicKeyCredentialUserEntity provide(Authentication authentication) {
            if(authentication == null){
                return null;
            }
            String username = authentication.getName();
            return new PublicKeyCredentialUserEntity(
                    username.getBytes(StandardCharsets.UTF_8),
                    username,
                    username
            );
        }
    }

Instead of making more complex our existing WebSecurityConfigurerAdapter, I would rather adding AttestationOptionsEndpointFilter logic as a Controller, through the existing securityFilterChains.

**Describe the solution you'd like**
Be provided a Controller (or anything not requiring to modify existing Filters) to respond similarly to AttestationOptionsEndpointFilter.

**Describe alternatives you've considered**
Writing this, I feel like I can code given Controller by myself. But it is cumbersome to rely on the same configuration as the one in my WebAuthn4JWebSecurityConfigurerAdapter given it relies on a WebAuthnLoginConfigurer (which is not @Bean friendly).

**Additional context**
(As a side-note, we encountered issues as given Filter respond a AttestationOptions even if the HttpMethod is not GET (which is unexpected especially if the method is OPTIONS)). Given a Controller, we sould pick esplicitely @GetMapping (and @PostMapping?)

**Comment by blacelle** [comment]
I handled this through:

	// https://github.com/webauthn4j/webauthn4j/issues/700
	@Bean
	public AttestationOptionsProvider attestationOptionsProvider(ApplicationContext appContext,
			ObjectPostProcessor<Object> objectPostProcessor,
			AuthenticationManagerBuilder authenticationBuilder) throws Exception {
		Map<Class<?>, Object> sharedObjects = Collections.singletonMap(ApplicationContext.class, appContext);

		// We make a fake HttpSecurity to replay our configuration
		HttpSecurity http = new HttpSecurity(objectPostProcessor, authenticationBuilder, sharedObjects);

		// Replay our configuration
		configureWebAuthn4J(env, http);

		// Return a AttestationOptionsProvider as it would have been instantiated by WebAuthnLoginConfigurer
		return WebAuthn4hHacker.WebAuthnConfigurerUtil.newAttestationOptionsProvider(http);
	}

	@Bean
	public AttestationOptionsProviderController attestationOptionsProviderController(
			AuthenticationTrustResolver trustResolver,
			AttestationOptionsProvider attestationOptionsProvider) {
		return new AttestationOptionsProviderController(trustResolver, attestationOptionsProvider);
	}

Given class in webauthn4j packahe to access package-friendly methods:

```
package com.webauthn4j.springframework.security.config.configurers;

import org.springframework.security.config.annotation.web.HttpSecurityBuilder;

import com.webauthn4j.springframework.security.authenticator.WebAuthnAuthenticatorService;
import com.webauthn4j.springframework.security.challenge.ChallengeRepository;
import com.webauthn4j.springframework.security.options.AttestationOptionsProvider;
import com.webauthn4j.springframework.security.options.AttestationOptionsProviderImpl;
import com.webauthn4j.springframework.security.options.RpIdProvider;

public class WebAuthn4hHacker {

	public static final class WebAuthnConfigurerUtil {

		public static <H extends HttpSecurityBuilder<H>> RpIdProvider getRpIdProviderOrNull(H http) {
			return com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil
					.getRpIdProviderOrNull(http);
		}

		public static <
				H extends HttpSecurityBuilder<H>> WebAuthnAuthenticatorService getWebAuthnAuthenticatorServiceOrThrowException(
						H http) {
			return com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil
					.getWebAuthnAuthenticatorServiceOrThrowException(http);
		}

		public static <H extends HttpSecurityBuilder<H>> ChallengeRepository getChallengeRepositoryOrCreateNew(H http) {
			return com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil
					.getChallengeRepositoryOrCreateNew(http);
		}

		// Like
		// com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil.getAttestationOptionsProviderOrCreateNew(H)
		// But without trying from the ApplicationContext
		public static <
				H extends HttpSecurityBuilder<H>> AttestationOptionsProvider newAttestationOptionsProvider(H http) {
			return new AttestationOptionsProviderImpl(getRpIdProviderOrNull(http),
					getWebAuthnAuthenticatorServiceOrThrowException(http),
					getChallengeRepositoryOrCreateNew(http));
		}

	};

}

```

**Comment by blacelle** [comment]
I see it is quite simple to provide various WebAuthn4J beans, and get them used automatically by WebAuthnLoginConfigurer, but it is then unclear what should be removed from `.apply(WebAuthnLoginConfigurer.webAuthnLogin())` custom configuration.

Maybe a next-step for this project would be to rely on an AutoConfiguration, provided a default set of Beans, easily overridable?

**Comment by ynojima** [comment]
> (As a side-note, we encountered issues as given Filter respond a AttestationOptions even if the HttpMethod is not GET (which is unexpected especially if the method is OPTIONS)). 

This need to be corrected. Thank you for let me know.

> While we initially added an additional WebSecurityConfigurerAdapter dedicated to WebAuthn4J purposes, it does not work as simply as that as AttestationOptionsEndpointFilter has to receive a proper Authentication (from a not-WebAuthn4J filter) to return a proper userId.

I'm still not sure why you cannot use `AttestationOptionsEndpointFilter`/`AssertionOptionsEndpointFilter`, but if you don't want to use it, yes, defining your own Controller and injecting `AttestationOptionsProvider`/`AssertionOptionsProvider` is the right direction.
Since Spring Security 5.7 deprecated `WebSecurityConfigurerAdapter`, our sample code doesn't rely on `WebSecurityConfigurerAdapter`:
https://github.com/webauthn4j/webauthn4j-spring-security/blob/0.7.6.RELEASE/samples/mpa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/app/config/WebSecurityConfig.java
If `WebSecurityConfigurerAdapter` is the issue, please check it out.

> Describe the solution you'd like
> Be provided a Controller

As far as I remember, `spring-webmvc`(not `spring-web`) is required to implement `Controller`, but since Spring Security doesn't use it, WebAuthn4J Spring Security doesn't use it too.
Please check Spring Security endpoint classes. everything is implemented as a filter, not Spring MVC Controller.
This is a policy as a library, you may feel free to implement your endpoints with Controller in your application.

> But it is cumbersome to rely on the same configuration as the one in my WebAuthn4JWebSecurityConfigurerAdapter given it relies on a WebAuthnLoginConfigurer (which is not @bean friendly).

Do you mean it is hard to use `AttestationOptionsProvider` and `AssertionOptionsProvider` from your Controllers because `WebAuthnLoginConfigurer` doesn't expose them as beans?

**Comment by blacelle** [comment]
> I'm still not sure why you cannot use AttestationOptionsEndpointFilter/AssertionOptionsEndpointFilter

My only motivation is to keep Filter-Chains as simple as possible. We try to restrict Filters to features _requiring_ filtering (e.g. security, headers-enrichment). Here, I believe AttestationOptionsEndpointFilter is some kind of final Filter, i.e. it returns a result, and break the chain (if it is concerned by query path): in Spring world, I would naturally implement this as a Controller.

---

> As far as I remember, spring-webmvc(not spring-web) is required to implement Controller, but since Spring Security doesn't use it, WebAuthn4J Spring Security doesn't use it too.

Interesting. I now understand the motivation for the current design.

---

> This is a policy as a library, you may feel free to implement your endpoints with Controller in your application.

Yep. I've provided code for our own workaround. It may help others anyway :).

---

> Do you mean it is hard to use AttestationOptionsProvider and AssertionOptionsProvider from your Controllers because WebAuthnLoginConfigurer doesn't expose them as beans?

Yes, it is harder as I feel important to make sure our controller and the default Filters rely on the same beans (e.g. to make sure the whole rely on the same configuration (ids, realms, keys)). As this is a strong motivation of mine, I've done the following to ensure same configuration:

```
@Bean
public AttestationOptionsProvider attestationOptionsProvider(ApplicationContext appContext,
		ObjectPostProcessor<Object> objectPostProcessor,
		AuthenticationManagerBuilder authenticationBuilder) throws Exception {
	Map<Class<?>, Object> sharedObjects = Collections.singletonMap(ApplicationContext.class, appContext);

	// We make a fake HttpSecurity to replay our configuration
	HttpSecurity http = new HttpSecurity(objectPostProcessor, authenticationBuilder, sharedObjects);

	// Replay our configuration
	configureWebAuthn4J(env, http);

	// Return a AttestationOptionsProvider as it would have been instantiated by WebAuthnLoginConfigurer
	return WebAuthn4hHacker.WebAuthnConfigurerUtil.newAttestationOptionsProvider(http);
}
```

Where `configureWebAuthn4J(env, http);` is a usual WebAuth4j configuration.

**Comment by blacelle** [comment]
> As far as I remember, spring-webmvc(not spring-web) is required to implement Controller, but since Spring Security doesn't use it, WebAuthn4J Spring Security doesn't use it too.

Given provided implementation, 

```
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
```

seems to require only spring-web, not spring-webmvc.

Spring-webmvc is one way to expose the controller (as an alternative to spring-reactive): It is up to the project relying on your Controller to decide to expose them with spring-webmvc, or spring-reactive (or something else).

Hence, it looks OK to me that a project like WebAuthn4J provides some Controllers.

**Comment by blacelle** [comment]
> As far as I remember, spring-webmvc(not spring-web) is required to implement Controller, but since Spring Security doesn't use it, WebAuthn4J Spring Security doesn't use it too.

Yes. Fact is I feel a related discomfort with a Filter like https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java

However most Spring-Security Filters are focused on enriching the current request. While in the case of WebAuthn, there is specific routes expected to return specific results. 

Quite similarly, for OAuth2, I would expect the JwkSet to be provided as a Controller, not through a Filter.

[Here, it is provided through a Filter.](https://github.com/spring-projects/spring-authorization-server/blob/main/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/NimbusJwkSetEndpointFilter.java)
[Here it is suggested as a Controller](https://www.baeldung.com/spring-security-oauth2-jws-jwk#9-creating-the-jwk-set-endpoint)

-> It is just style.

---

Thinking again about it: 

> I'm still not sure why you cannot use AttestationOptionsEndpointFilter/AssertionOptionsEndpointFilter

One of my motivation here is to keep WebAuth4J features in its own SecurityFilterChain (away from the existing Bearer-SecurityFilterChain). However, AttestationOptionsProvider is used to return a json which includes a block specific to the current user/Authentication (based on a Bearer token): hence, this code has to be served through a Bearer-SecurityFilterChain. I end feeling like I could keep WebAuth4J own additional SecurityFilterChain, but I need AttestationOptionsProvider to be served inside the Bearer-SecurityFilterChain. I might be telling gibberish, underlining my lack of maturity how to implement WebAuthn in a project xD, as it is not impossible that WebAuthn4H **has to** added right into the Bearer-SecurityFilterChain.

**Comment by ynojima** [comment]
>Yes. Fact is I feel a related discomfort with a Filter like https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java
>
>However most Spring-Security Filters are focused on enriching the current request. While in the case of WebAuthn, there is specific routes expected to return specific results.
>
>Quite similarly, for OAuth2, I would expect the JwkSet to be provided as a Controller, not through a Filter.

I understand how you feel, but it seems using filter is the Spring Security style.
For example, Spring Security SAML uses a filter for presenting Metadata.
https://github.com/spring-projects/spring-security-saml/blob/main/core/src/main/java/org/springframework/security/saml/metadata/MetadataDisplayFilter.java

WebAuthn4J Sring Security won't provide a controller.

If you want `AttestationOptionsProvider` or `AssertionOptionsProvider` as beans to use from your controller, just define them as beans. WebAuthn4J Spring Security JavaConfig(WebAuthnLoginConfigurer) will pick them up from ApplicationContext.
