### ISSUE TITLE
Unclear Sample Application - /api/profile seems public

### ISSUE THREAD

**Issue by blacelle** [webauthn4j/webauthn4j-spring-security#1035]
Looking at the code, I spotted:

https://github.com/webauthn4j/webauthn4j-spring-security/blob/90e9566cbb84dd8fa91f487bebb15d126097eb82/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/app/config/WebSecurityConfig.java#L142

I interpret this as POST on /api/profile is public, while I would expect this route to be private. Did I miss something?

Thanks

**Comment by ynojima** [comment]
I overlooked this issue, sorry.
Since this is a sample application, account creation endpoint is open to public.
