### ISSUE TITLE
No possibility to provide custom OriginValidator implementation

### ISSUE THREAD

**Issue by mchmielarz** [webauthn4j/webauthn4j-spring-security#1088]
Since `RegistrationDataValidator` is created "manually" in the constructor of `WebAuthnRegistrationManager` class it is not possible to set a custom `OriginValidator` implementation in `RegistrationDataValidator`. I would need to provide my own that omits checks of port numbers when comparing origin values.

The same would apply to `AuthenticationDataValidator` which is created inside of `WebAuthnAuthenticationManager` class.

**Comment by ynojima** [comment]
Since you can get `RegistrationDataValidator` from `WebAuthnRegistrationManager` with `WebAuthnRegistrationManager#getRegistrationDataValidator`, `RegistrationDataValidator#setOriginValidator` can be used to set your custom `OriginValidator`.
