### ISSUE TITLE
org.owasp:dependency-check-gradle needs NVD_API_KEY now

### ISSUE THREAD

**Issue by AxelNennker** [webauthn4j/webauthn4j-spring-security#1360]
NIST requires an API key now:
https://nvd.nist.gov/developers/request-an-api-key

dependeny-check is really slow without an NVD_API_KEY

Please request an api key and use it
https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

**Comment by ynojima** [comment]
Thank you for the info. Since GitHub provides similar feature, I will remove owasp dependency check plugin on this occasion.
https://github.com/webauthn4j/webauthn4j-spring-security/pull/1361
