### ISSUE TITLE
请教下哪个版本支持jdk11的呀

### ISSUE THREAD

**Issue by cumtcool007** [webauthn4j/webauthn4j-spring-security#1550]
最新的版本都是jdk11的，我们项目中目前还都是jdk11，我需要使用哪个包可支持jdk11

**Comment by ynojima** [comment]
Please file an issue in English.

**Comment by cumtcool007** [comment]
The latest version supports JDK17, and currently our project is still using JDK11. Which package do I need to use to support JDK11

**Comment by ynojima** [comment]
From WebAuthn4J Spring Security [0.9.0.RELEASE](https://github.com/webauthn4j/webauthn4j-spring-security/releases/tag/0.9.0.RELEASE), it depends Spring Security 6.0 or later, which requires JDK17.
Please use  WebAuthn4J Spring Security [0.8.0.RELEASE](https://github.com/webauthn4j/webauthn4j-spring-security/releases/tag/0.8.0.RELEASE) if you are using Spring Security 5.x or before and JDK 11.

**Comment by cumtcool007** [comment]
thanks，[webauthn4j](https://github.com/webauthn4j/webauthn4j)    latest version supports JDK15(I'm not sure if it's true ), and currently our project is still using JDK11. Which package do I need to use to support JDK11

**Comment by ynojima** [comment]
Are you asking which package to use? not which version to use?
If you plan to use it within an application secured by Spring Security, you use use WebAuthn4J Spring Security (`webauthn4j-spring-security-core` module). It provides useful classes to integrate webauthn4j with Spring Security.
If you plan to use it within a non Spring application, you need to use WebAuthn4J directly (`webauthn4j-core` module).

**Comment by cumtcool007** [comment]
Yes, I want to introduce Java packages in Maven, but I don't know which version to switch to. The current project is JDK11

**Comment by cumtcool007** [comment]
[webauthn4j](https://github.com/webauthn4j/webauthn4j)    and  https://github.com/webauthn4j/webauthn4j-spring-security      
 which version to switch to by Maven for jdk11

**Comment by ynojima** [comment]
If you use `webauthn4j-spring-security-core`, please use its [0.9.0.RELEASE](https://github.com/webauthn4j/webauthn4j-spring-security/releases/tag/0.9.0.RELEASE). Since `webauthn4j-spring-security-core` will depends `webauthn4j-core`, you don't need to introduce `webauthn4j-core` explicitly.
