### ISSUE TITLE
Sample application not available

### ISSUE THREAD

**Issue by Ant00000ny** [webauthn4j/webauthn4j-spring-security#1578]
after 00a451157ce8dd6d2ac4c55ec1c4919912920dbb, the command in README

```shell
./gradlew samples:spa:bootRun
```
is no longer runnable.

**Comment by ynojima** [comment]
Thank you for pointing this out.
I made a pull-request to update the documents: https://github.com/webauthn4j/webauthn4j-spring-security/pull/1580
