### ISSUE TITLE
apple-appattest 

### ISSUE THREAD

**Issue by nehox** [webauthn4j/webauthn4j-spring-security#538]
had you some doc / exemple or test for apple-appatest ? 
i can't find any help in this doc : https://webauthn4j.github.io/webauthn4j-spring-security/en/

**Comment by ynojima** [comment]
WebAuthn4J Spring Security doesn't provide support for Apple App Attest.
Apple App Attest is an API to attest an request from an App is valid, but WebAuthn4J Spring Security is designed for authentication.
If you would like to use Apple App Attest in your Spring based application, use webauthn4j-device-check directly in your application.
https://webauthn4j.github.io/webauthn4j/en/#apple-app-attest-verification

**Comment by nehox** [comment]
I'm looking to use the appattest format to do a webauthn attestation and I thought this library could do that.

**Comment by ynojima** [comment]
If you are interested in 'apple' anonymous attestation, which is for WebAuth, webauthn4j-spring-security can be used.
