### ISSUE TITLE
The allowCredentials list is always empty with InMemoryWebAuthnAuthenticatorManager

### ISSUE THREAD

**Issue by sbelikov** [webauthn4j/webauthn4j-spring-security#575]
Key type mismatch in AssertionOptionsProvider and InMemoryWebAuthnAuthenticatorManager

It looks like the AssertionOptionsProvider passes String as key for credentials lookup, when InMemoryWebAuthnAuthenticatorManager expect keys of type User. For this reason, the call  

https://github.com/webauthn4j/webauthn4j-spring-security/blob/ea916a83208f0d3bdcdf2d4417d6d38f97d47f15/webauthn4j-spring-security-core/src/main/java/com/webauthn4j/springframework/security/options/AssertionOptionsProviderImpl.java#L161

always returns the empty list.

**Comment by ynojima** [comment]
`InMemoryWebAuthnAuthenticatorManager` doesn't assume key type `User`. Key type is defined as `Object` and aligning is up to caller's responsibility.
