### ISSUE TITLE
The UserVerificationStrategy is not configurable in WebAuthnProcessingFilter

### ISSUE THREAD

**Issue by sbelikov** [webauthn4j/webauthn4j-spring-security#576]
In my application there is a use case that requires only User Presence validation wen user is not authentciated yet. Would it be possible to make this strategy injectable into the filter? It would be greatly appreciated.

**Comment by ynojima** [comment]
Thank you for pointing out. Your request sounds reasonable, and I cannot recall why I didn't implement it.
