### ISSUE TITLE
MPA sample should use the username instead of user to create a WebAuthnAuthenticator

### ISSUE THREAD

**Issue by trimoq** [webauthn4j/webauthn4j-spring-security#634]
In the MPA sample, a `WebAuthnAuthenticator` gets created from the variable `user`.
https://github.com/webauthn4j/webauthn4j-spring-security/blob/1564c361bc5659ba3a8b9e7a76b608987a2e7b9b/samples/mpa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/app/web/WebAuthnSampleController.java#L155-L158

But `AssertionOptionsProviderImpl `passes `authentication.getName()` to the `WebAuthnAuthenticatorService` when looking up credentials.

https://github.com/webauthn4j/webauthn4j-spring-security/blob/1564c361bc5659ba3a8b9e7a76b608987a2e7b9b/webauthn4j-spring-security-core/src/main/java/com/webauthn4j/springframework/security/options/AssertionOptionsProviderImpl.java#L161-L163

Since the in-memory implementation is used in the sample, we search for the name of the current `Authentication` in the map.

https://github.com/webauthn4j/webauthn4j-spring-security/blob/1564c361bc5659ba3a8b9e7a76b608987a2e7b9b/webauthn4j-spring-security-core/src/main/java/com/webauthn4j/springframework/security/authenticator/InMemoryWebAuthnAuthenticatorManager.java#L47-L49

Since the sample code stored the whole `UsernamePasswordAuthenticationToken`, this will never match and a user authenticated in a first step will not be presented with allowed credentials.

To allow matching to work, I would propose to change the sample code to use the users name instead of the whole user.
If you think this is the correct way, I am happy to create a PR for it.

**Comment by trimoq** [comment]
By changing only the sample, we do not make assumptions about the used data type, as discussed in https://github.com/webauthn4j/webauthn4j-spring-security/issues/575.

**Comment by ynojima** [comment]
Sorry for late response. As you pointed out, this needs to be fixed. I'll appreciate if you create a pull-request for it.
